apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurepvc-logs
  namespace: airflow-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi